- harness/src/main/java/org/apache/geode/perftest/analysis/BenchmarkRunAnalyzer.java
- harness/src/main/java/org/apache/geode/perftest/yardstick/YardstickTask.java
- harness/src/test/java/org/apache/geode/perftest/analysis/BenchmarkRunAnalyzerTest.java
- harness/src/test/java/org/apache/geode/perftest/yardstick/YardstickTaskTest.java
Yardstick creates a subdirectory, so find the files in that directory
> GEODE-6086: Looking for the output files in the correct location

- infrastructure/google_cloud/README.md
> Clean up prerequisites documentation.

- harness/src/main/java/org/apache/geode/perftest/TestConfig.java
- harness/src/main/java/org/apache/geode/perftest/jvms/JVMLauncher.java
- harness/src/main/java/org/apache/geode/perftest/jvms/JVMMapping.java
- harness/src/main/java/org/apache/geode/perftest/jvms/RemoteJVMFactory.java
- harness/src/main/java/org/apache/geode/perftest/runner/DefaultTestRunner.java
- harness/src/test/java/org/apache/geode/perftest/TestRunnerIntegrationTest.java
- harness/src/test/java/org/apache/geode/perftest/TestRunnerJUnitTest.java
- harness/src/test/java/org/apache/geode/perftest/jvms/RemoteJVMFactoryIntegrationTest.java
- harness/src/test/java/org/apache/geode/perftest/jvms/RemoteJVMFactoryTest.java
- harness/src/test/java/org/apache/geode/perftest/runner/SharedContextTest.java
Allowing performance tests to set the JVM options for each role in the
test.
> Allowing JVM options to be set by test

- geode-benchmarks/build.gradle
* Create unique results folder with timestamp if default output file is not set.
> GEODE-6180: Create unique results folder.

- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/PartitionedGetBenchmark.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/PartitionedPutBenchmark.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/ReplicatedGetBenchmark.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/ReplicatedPutBenchmark.java
- harness/src/main/java/org/apache/geode/perftest/TestConfig.java
- harness/src/main/java/org/apache/geode/perftest/TestRunners.java
- harness/src/main/java/org/apache/geode/perftest/runner/DefaultTestRunner.java
- harness/src/test/java/org/apache/geode/perftest/TestRunnerIntegrationTest.java
- harness/src/test/java/org/apache/geode/perftest/TestRunnerJUnitTest.java
* Removed name from TestConfig
* Test name derieved from the classname.
> GEODE-6181: Testname derieved from the Class name.

- geode-benchmarks/src/main/java/benchmark/geode/data/CollectionHolder.java
- geode-benchmarks/src/main/java/benchmark/geode/data/Portfolio.java
- geode-benchmarks/src/main/java/benchmark/geode/data/Position.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/PrePopulateRegion.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/PutTask.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/StartClient.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/StartServer.java
- geode-benchmarks/src/test/java/org/apache/geode/benchmark/tasks/PrePopulateRegionTest.java
- harness/src/main/java/org/apache/geode/perftest/TestRunners.java
* Changing the test data package name to be able to run old geode versions
* Test create smaller JVM for travis to be able to run it.
> Changing the test parameters

- infrastructure/scripts/aws/run_against_baseline.sh
- infrastructure/scripts/aws/run_tests.sh
Name the cli options for running the benchmark. Support either a version
number or a branch/commit ref. Use version to fetch previously built
releases, to avoid rebuilding them every time.
Signed-off-by: Jacob Barrett <jbarrett@pivotal.io>
> GEODE-6276: use named cli options for scripts

- harness/src/main/java/org/apache/geode/perftest/analysis/Analyzer.java
- harness/src/main/java/org/apache/geode/perftest/analysis/BenchmarkRunResult.java
* Change ratio to difference
* Add difference calculation to ProbeResult
* Fail analyzeRun task if average latency difference is >= 5%
> GEODE-6147 - Fail benchmark task if average latency change is 5+%

- build.gradle
- gradle/resolve-dependencies.gradle
> Add ability to fetch dependencies.

- infrastructure/scripts/aws/run_against_baseline.sh
- infrastructure/scripts/aws/run_tests.sh
* Add default for branch under test
* Fetch dependencies before running benchmarks.
> Fix defaults and dependencies.

- infrastructure/scripts/aws/run_against_baseline.sh
- infrastructure/scripts/aws/run_tests.sh
> Adjust getopt parameters and fix git checkout method.

- infrastructure/scripts/aws/run_against_baseline.sh
- infrastructure/scripts/aws/run_tests.sh
- Arguments after -- will be passed to benchmark gradle task.
Example: Add `--tests MyTest` to run specific benchmark.
Authored-by: Jacob Barrett <jbarrett@pivotal.io>
> GEODE-6411: Allow alternative repo

- harness/src/main/java/org/apache/geode/perftest/runner/DefaultTestRunner.java
Co-authored-by: Sean Goller <sgoller@pivotal.io>
Co-authored-by: Nabarun Nag <nabarunnag@pivotal.io>
> Clean up metadata generation. Add all test names to metadata.

- infrastructure/scripts/aws/run_against_baseline.sh
Co-authored-by: Sean Goller <sgoller@pivotal.io>
Co-authored-by: Nabarun Nag <nabarunnag@pivotal.io>
> Change bash tests to double brackets and fix baseline branch test.

- infrastructure/scripts/aws/README.md
Updated the README.md to address some issues I found as a new team member.
> GEODE-6508: update aws README.md

- infrastructure/scripts/aws/README.md
* add initial configuration information for YourKit
* fix path to private key when setting up connection authentication in
YourKit
> update profiling instructions in the readme

- harness/build.gradle
- harness/src/main/java/org/apache/geode/perftest/runner/DefaultTestRunner.java
- infrastructure/scripts/aws/fetch_results.sh
- infrastructure/scripts/aws/run_tests.sh
- infrastructure/scripts/aws/scan_builds.sh
- infrastructure/scripts/aws/submit_benchmark.py
- infrastructure/scripts/aws/submit_results.sh
First pass at database submission, as well as fetching more metadata via java.
> Metadata generation tweaks and database submission code

- infrastructure/scripts/aws/submit_benchmark.py
> Finish up unique identification of builds.

- infrastructure/build.gradle
- infrastructure/src/main/java/org/apache/geode/infrastructure/aws/ExpireClusters.java
Co-authored-by: Helena Bales <hbales@pivotal.io>
Co-authored-by: Sean Goller <sgoller@pivotal.io>
> find and destroy clusters that were started more than 7 days ago

- infrastructure/src/main/java/org/apache/geode/infrastructure/aws/ExpireClusters.java
Co-authored-by: Helena Bales <hbales@pivotal.io>
Co-authored-by: Sean Goller <sgoller@pivotal.io>
> RAT fixes.

- harness/build.gradle
- harness/src/main/java/org/apache/geode/perftest/analysis/Analyzer.java
- infrastructure/scripts/aws/analyze_tests.sh
- infrastructure/scripts/aws/run_against_baseline.sh
Pick a new high watermark commit based on the benchmark results and print to the screen.
> Automatically choose the new high watermark commit

- .gitignore
- README.md
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/parameters/GeodeProperties.java
- harness/build.gradle
- harness/src/main/java/org/apache/geode/perftest/jvms/JVMLauncher.java
- harness/src/main/java/org/apache/geode/perftest/jvms/RemoteJVMFactory.java
- infrastructure/scripts/aws/README.md
Tracker #167072556
Co-authored-by: Murtuza Boxwala <mboxwala@pivotal.io>
Co-authored-by: Kamilla Aslami <kaslami@pivotal.io>
> Generate a self-signed certificate for SSL

- .gitignore
- README.md
- geode-benchmarks/build.gradle
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/parameters/GeodeProperties.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/security/ExampleAuthInit.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/StartClient.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/StartLocator.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/StartServer.java
- geode-benchmarks/src/main/java/org/apache/geode/benchmark/topology/ClientServerTopology.java
- geode-benchmarks/src/test/java/org/apache/geode/benchmark/topology/ClientServerTopologyTest.java
- harness/src/main/java/org/apache/geode/perftest/jvms/RemoteJVMFactory.java
- harness/src/main/resources/security.json
- infrastructure/scripts/aws/README.md
Co-authored-by: Murtuza Boxwala <mboxwala@pivotal.io>
Co-authored-by: Kamilla Aslami <kaslami@pivotal.io>
> User can run benchmarks with SecurityManager

- build.gradle
- etc/greclipse.properties
- geode-benchmarks/build.gradle
- gradle/rat.gradle
- gradle/resolve-dependencies.gradle
- gradle/spotless.gradle
- harness/build.gradle
- infrastructure/build.gradle
The current spotless configuration doesn't apply any code style rules to gradle/groovy files and any files inside buildSrc directory.
>  Fixed spotless configuration to support groovy and gradle.

- infrastructure/scripts/aws/run_tests.sh
- infrastructure/src/main/java/org/apache/geode/infrastructure/aws/DestroyCluster.java
- infrastructure/src/main/java/org/apache/geode/infrastructure/aws/LaunchCluster.java
Co-authored-by: Kamilla Aslami <kaslami@pivotal.io>
Co-authored-by: Jacob Barrett <jbarrett@pivotal.io>
> Create dedicated hosts

- geode-benchmarks/build.gradle
- harness/src/main/java/org/apache/geode/perftest/analysis/Analyzer.java
- infrastructure/scripts/aws/run_against_baseline.sh
* write failed tests to a file
* enable all benchmarks
* update help message for --ci option in run_against_baseline.sh
> GEODE-7554: Add retry mechanism for failed tests

- infrastructure/scripts/aws/image/packer.json
Signed-off-by: Sean Goller <sgoller@pivotal.io>
> install JDK11 on image and fix image script issue with dpkg

- infrastructure/scripts/aws/run_against_baseline.sh
modify output dir to be unique for running in CI
> fix output dir motification

- infrastructure/build.gradle
- infrastructure/scripts/aws/image/packer.json
- infrastructure/scripts/aws/launch_cluster.sh
- infrastructure/src/main/java/org/apache/geode/infrastructure/aws/LaunchCluster.java
Add the ability to choose what purpose tag is searched for when launching benchmarks.
> GEODE-8348: Add support for customizable purpose tag.

- infrastructure/build.gradle
- infrastructure/scripts/aws/destroy_cluster.sh
- infrastructure/scripts/aws/launch_cluster.sh
- infrastructure/src/main/java/org/apache/geode/infrastructure/aws/AwsBenchmarkMetadata.java
- infrastructure/src/main/java/org/apache/geode/infrastructure/aws/LaunchCluster.java
Reverts apache/geode-benchmarks#132
> Revert "allow AMI picking with arbitrary username accounts"
