settings.gradle

I'm not sure if this is the best name for the project, but it makes more sense than what it was.

Change project name to geode-benchmarks.

---

harness/build.gradle
harness/src/main/java/org/apache/geode/perftest/yardstick/Clock.java
harness/src/main/java/org/apache/geode/perftest/yardstick/HdrHistogramProbe.java
harness/src/main/java/org/apache/geode/perftest/yardstick/YardstickTask.java
harness/src/test/java/org/apache/geode/perftest/yardstick/HdrHistogramProbeTest.java

Adding a new probe that uses HdrHistogram to generate a summary with a
mean and 99th percentile latency.
HdrHistogram should be more accurate than yardsticks histogram probe.
This probe currently just reports a one line summary, but we could
consider replacing the existing percentile and throughtput probes with
this thing in the future - it has its own file format for recording per
sample histograms.

GEODE-6081: Probe that uses HdrHistogram

---

harness/build.gradle
harness/src/main/java/org/apache/geode/perftest/analysis/Analyzer.java
harness/src/main/java/org/apache/geode/perftest/analysis/BenchmarkRunAnalyzer.java
harness/src/test/java/org/apache/geode/perftest/analysis/BenchmarkRunAnalyzerTest.java

This change adds the analyzeRun gradle target, which, when passed a baseline
result directory and test result directory via --args, will analyze the output
and report the variation of the test from the baseline.
Sample output: 
```
MacBook-Pro-2:geode-performance browe$ ./gradlew analyzeRun --args "/Users/browe/project/geode-performance/geode-benchmarks/output2 /Users/browe/project/geode-performance/geode-benchmarks/output"
> Task :harness:analyzeRun
Running analyzer
Comparing test result at /Users/browe/project/geode-performance/geode-benchmarks/output2 to baseline at /Users/browe/project/geode-performance/geode-benchmarks/output
-- PartitionedPutBenchmark --
average ops/second
Result: 47386.93220338983
Baseline: 46237.745762711864
Relative performance: 1.0248538595842343
99th percentile …
```

GEODE-6086: Adding a tool to allow command line analysis of test runs

---

harness/src/main/java/org/apache/geode/perftest/analysis/BenchmarkRunAnalyzer.java
harness/src/main/java/org/apache/geode/perftest/analysis/ProbeResultParser.java
harness/src/main/java/org/apache/geode/perftest/yardstick/analysis/YardstickHdrHistogramParser.java
harness/src/main/java/org/apache/geode/perftest/yardstick/analysis/YardstickPercentileSensorParser.java
harness/src/main/java/org/apache/geode/perftest/yardstick/analysis/YardstickThroughputSensorParser.java
harness/src/test/java/org/apache/geode/perftest/analysis/BenchmarkRunAnalyzerTest.java

This change modifies the ProbeResultParser interface to return a list of
ResultData objects.  It takes advantage of this new functionality to return
6 results from the HDRHistogramParser (median latency, 90, 99, 99.9 percentile
latencies, average latency, and latency standard deviation).  This is probably
too noisy for the long run, but could prove useful as we evaluate different
platforms.
This change also changes the BenchmarkRunAnalyzer (invoked via gradlew
analyzeRun) to take the baseline directory as its first argument.

GEODE-6145: Allow multiple results for a single probe analyzer

---

harness/src/test/java/org/apache/geode/perftest/infrastructure/ssh/SshInfrastructureFactoryTest.java

SshInfrastructure was trying to copy data to nodes that aren't needed,
resulting in failures if the user passed extra nodes.

Ignoring extra hosts in SshInfrastructure

---

infrastructure/google_cloud/destroy_cluster.sh
infrastructure/google_cloud/launch_cluster.sh

This launches the cluster using single-tenant nodes instead of random instances.

Convert to sole tenant style cluster.

---

geode-benchmarks/src/main/java/org/apache/geode/benchmark/parameters/GeodeProperties.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/parameters/JVMParameters.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/StartClient.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/StartLocator.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/StartServer.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/PartitionedGetBenchmark.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/PartitionedPutBenchmark.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/ReplicatedGetBenchmark.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/ReplicatedPutBenchmark.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/topology/ClientServerTopology.java

Setting some geode properties on all benchmarks to improve the performance and enable additional statistics.
Refactoring the location of JVMParameters and the util package.

GEODE-6172: Configure geode properties for benchmarks

---

geode-benchmarks/build.gradle
geode-benchmarks/src/main/java/org/apache/geode/benchmark/parameters/JVMParameters.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/CreatePartitionedRegion.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/PrePopulateRegion.java
geode-benchmarks/src/test/java/org/apache/geode/benchmark/tasks/PrePopulateRegionTest.java

Prepopulating the region used to occur by means of puts from every
server for every key in the specified range. This resulted in
unnecessarily conflicting puts.
To improve performance of the setup, PrePopulateRegion.run() now divides
the key range as evenly as possible between all servers in the cluster,
prepares the data in a map, then puts the map to the region using
putAll().
The changes result in an observable improvement in performance.

GEODE-6148: improve performance of Prepopulate

---

geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/PrePopulateRegion.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/PartitionedGetBenchmark.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/PartitionedPutBenchmark.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/ReplicatedGetBenchmark.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/ReplicatedPutBenchmark.java

We see an occasional delay/hang when simply clearing and reusing the same
hashmap for multiple putAll requests.  This change creates a new hashmap every
time it starts a new batch.
This also increases the keyRange for the benchmarks from 10k to 1M.
Co-Authored-By: Helena Bales <hbales@pivotal.io>

GEODE-6233: Use a new hash-map for each PutAll batch in PrePopulateRegion

---

infrastructure/scripts/aws/run_against_baseline.sh
infrastructure/scripts/aws/run_tests.sh
infrastructure/src/main/java/org/apache/geode/infrastructure/aws/DestroyCluster.java

* Allow output directory to be overridden via commandline in
run_against_baseline.sh
* Change how branch/tag is checked out in run_tests.sh to support
SHA references as well
* Minor code cleanup in DestroyCluster class

GEODE-6135 - Changes to support running in CI

---

geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/PrePopulateRegion.java
harness/src/main/java/org/apache/geode/perftest/TestContext.java
harness/src/main/java/org/apache/geode/perftest/runner/DefaultTestContext.java
harness/src/main/java/org/apache/geode/perftest/runner/SharedContext.java

* New method added to get the number of members for each role.
* Calculating unique addresses for number of members caused an issue when all VMs are in the same physical machine.

GEODE-6243: New method to get number of members.

---

infrastructure/scripts/aws/README.md
infrastructure/scripts/aws/destroy_cluster.sh
infrastructure/scripts/aws/image/build_image.sh
infrastructure/scripts/aws/launch_cluster.sh
infrastructure/scripts/aws/run_tests.sh

* all scripts now use an AWS profile named `geode-benchmarks`.
* Add script to build AMI.

Use a dedicated separate profile to work with AWS.

---

infrastructure/scripts/aws/destroy_cluster.sh
infrastructure/scripts/aws/launch_cluster.sh
infrastructure/scripts/aws/run_tests.sh

* If AWS credentials are provided via environment variables, don't set
the profile.

Fix credentials management.

---

infrastructure/scripts/aws/run_tests.sh

Update the script for running tests on AWS to use the default version
number. The gradle parameters for specifying a custom version number
change in different versions. To have one script that works for all
versions, we use the default version number then get that version from
gfsh for use in benchmarks.
Co-Authored-By: jbarrett@pivotal.io

Update script for running tests on AWS

---

infrastructure/scripts/aws/analyze_tests.sh
infrastructure/scripts/aws/run_against_baseline.sh

* Add script to run analysis on an output directory
* Call analyze script from benchmark comparison script.

GEODE-6134 - Add analysis after running a benchmark comparison.

---

infrastructure/scripts/aws/run_against_baseline.sh
infrastructure/scripts/aws/run_tests.sh

Fail the benchmark job when it fails to build or get resources from
Maven.
Co-authored-by: Jacob Barrett <jbarrett@pivotal.io>

GEODE-6275: Fail Benchmark job when build fails

---

harness/src/main/java/org/apache/geode/perftest/yardstick/hdrhistogram/HdrHistogramWriter.java

* Create hgrm files from hlog file created by hdrhistogram.
* This new file is human readable and can be used by plotters to create graphs.

GEODE-6299: Create hgrm files from hlog

---

infrastructure/scripts/aws/analyze_tests.sh

This would cause the benchmark job in the geode pipeline to stay green even though the benchmark failed.

set -e so errors aren't masked.

---

geode-benchmarks/build.gradle

The variance is too large on this.

Exclude PartitionedIndexedQueryBenchmark.

---

geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/StartClient.java

The client was dropping connections to the server when it shouldn't
have. Setting the pool's idle-timeout from the default of 5 seconds to
have no limit resolved this issue.

GEODE-6394: set pool idle-timeout to be infinite

---

geode-benchmarks/build.gradle
harness/src/main/java/org/apache/geode/perftest/infrastructure/ssh/SshInfrastructure.java
harness/src/main/java/org/apache/geode/perftest/jvms/JVMLauncher.java
harness/src/main/java/org/apache/geode/perftest/jvms/rmi/ChildJVM.java
harness/src/main/java/org/apache/geode/perftest/jvms/rmi/Controller.java
harness/src/main/java/org/apache/geode/perftest/yardstick/YardstickTask.java
harness/src/test/java/org/apache/geode/perftest/jvms/rmi/ChildJVMTest.java

* Store the GC logs in a file.
* Print the GC logs in the System.out / System.err in parallel while the benchmark is being executed in parallel.
* Using a thread pool for execution of runAsync and not depend on fork join pools

GEODE-6444: Store GC logs in files

---

gradle/dependency-versions.properties
harness/build.gradle
harness/src/main/java/org/apache/geode/perftest/runner/DefaultTestRunner.java
harness/src/main/java/org/apache/geode/perftest/yardstick/hdrhistogram/HdrHistogramWriter.java
infrastructure/build.gradle
infrastructure/src/main/java/org/apache/geode/infrastructure/BenchmarkMetadata.java
infrastructure/src/main/java/org/apache/geode/infrastructure/aws/AwsBenchmarkMetadata.java
infrastructure/src/main/java/org/apache/geode/infrastructure/aws/DestroyCluster.java
infrastructure/src/main/java/org/apache/geode/infrastructure/aws/LaunchCluster.java
infrastructure/src/main/java/org/apache/geode/infrastructure/aws/MetadataInstaller.java

* Tests now output metadata if the metadata file doesn't exist.
* benchmark run metadata.json is actually json.
* Create configuration directory to store cluster information.
* Move SSH private key for cluster to configuration directory.
* Create metadata for cluster, currently including an instance ID and
the list of IPs in the cluster.
* Delete metadata when the cluster is destroyed.

Refactor metadata production and management.

---

geode-benchmarks/build.gradle
infrastructure/scripts/aws/run_against_baseline.sh
infrastructure/scripts/aws/run_tests.sh

Add long CLI options for scripts to run benchmarks on AWS instances.
Backwards compatible with previous short CLI options.
Signed-off-by: Robert Houghton <rhoughton@pivotal.io>

GEODE-6480: Just Do It Day: Use long cli options

---

infrastructure/build.gradle
infrastructure/scripts/aws/destroy_cluster.sh
infrastructure/scripts/aws/launch_cluster.sh
infrastructure/src/main/java/org/apache/geode/infrastructure/BenchmarkMetadata.java

Get the current username from system properties and add it to the aws
prefix to make the instance owners more immediately identifiable. This
should help reduce the number of instances that are left running with no
clear owner.

GEODE-6479: add username to aws keypair prefix

---

infrastructure/scripts/aws/destroy_cluster.sh
infrastructure/scripts/aws/launch_cluster.sh
infrastructure/scripts/aws/run_against_baseline.sh
infrastructure/scripts/aws/run_tests.sh

break out of the case statement so that options after '--' when running
tests and running against the baseline are passed on to gradle.

GEODE-6480: pass on CLI options after '--' for AWS scripts

---

infrastructure/scripts/aws/README.md

Update the readme to reflect all recent script changes, including
changing from positional to named arguments for launching and destroying
clusters, the addition of a --ci option for launching and destroying
clusters for use in continuous integration, and the addition of long
command line options for all scripts.

GEODE-6502: update README

---

geode-benchmarks/src/main/java/org/apache/geode/benchmark/parameters/GeodeProperties.java

Set membership timeout to be more resilient to benchmark load.
Setting membership timeout to 8s.

Set membership timeout to be more resilient to benchmark load

---

geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/PutAllTask.java

PutAllTask creates a hash map and fills it with the same key value. This produces a lot of garbage and results in high cpu load on client.

Fix hash map keys in PutAllTask

---

geode-benchmarks/build.gradle

The fix in PR #105 stabilized PartitionedPutAllBenchmark and ReplicatedPutAllBenchmark, so there is no need to exclude them anymore.

Enabled PutAll benchmarks

---

geode-benchmarks/build.gradle
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tasks/PutAllTask.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/tests/PartitionedPutAllBenchmark.java

Stabilize the putall tests by reducing the payload size to 100 entries, and decreasing the amount of garbage produced during the test on the client side.
This commit also re-enables the PutAll tests so they will run in CI and whenever all benchmarks are run.

stabilize putall tests

---

infrastructure/src/main/java/org/apache/geode/infrastructure/aws/LaunchCluster.java

Retry with timeouts, confirming the expected number of instances have
been allocated.
Retry with timeouts, confirming the expected number of instances are in
the running state.
Signed-off-by: Robert Houghton <rhoughton@pivotal.io>

Confirm and retry AWS instance allocations.

---

geode-benchmarks/build.gradle

NoopBenchmark has some fundamental issues that make it fail constantly.
In recent testing, it passed significantly more often that it has been
in Apache Geode CI, so it needs to be excluded until it can be fixed.

Exclude failing NoopBenchmark

---

gradle/wrapper/gradle-wrapper.properties

This is to match geode and geode-examples, which were updated to 5.4 as part of GEODE-6611 last April and October, respectively.
The benefit is just so you don't have to download multiple versions of gradle when switching between geode projects.

upgrade gradle from 5.0 to 5.4

---

infrastructure/scripts/aws/run_against_baseline.sh

reverting because the change to output file naming caused CI to not check the correct output for retried test runs.

revert change to output file naming

---

geode-benchmarks/build.gradle

- Add output after each test completes, as Travis declares a task hung
if no output is written for 10 minutes, which is longer than the build
and tests take to complete
Authored-by: Donal Evans <doevans@vmware.com>

Prevent Travis build timeout

---

geode-benchmarks/build.gradle

- This benchmark is unstable and does not produce reliable results. See
GEODE-8950 for further details.
Authored-by: Donal Evans <doevans@vmware.com>

Disable P2pPartitionedPutLongBenchmark

---

harness/build.gradle
harness/src/main/java/org/apache/geode/perftest/analysis/BenchmarkReader.java
harness/src/main/java/org/apache/geode/perftest/analysis/BenchmarkRunAnalyzer.java
harness/src/main/java/org/apache/geode/perftest/analysis/DumpResults.java
harness/src/main/java/org/apache/geode/perftest/analysis/ProbeResultParser.java
harness/src/main/java/org/apache/geode/perftest/yardstick/analysis/YardstickHdrHistogramParser.java
infrastructure/scripts/aws/dump_results.sh

This analyzer reads all of the benchmark results and prints one row for each
result. It does not do a comparison with a baseline.  For example:
dump_results.sh resultDir1 resultDir2 resultDir3
> Task :harness:dumpRun
Directory                                Benchmark                      ops/sec          avg latency(ms)  99%% latency(ms)
partition-10-1-thread-1K-values          PartitionBenchmark             52143.62         0.0763           0.1348
partition-10-16-thread-1K-value          PartitionBenchmark             232304.35        0.2747           0.6400
partition-10-4-thread-1K-values          PartitionBenchmark             134713.40        0.1182           0.2440

GEODE-9177: Adding a new analyzer that dumps data in a tabular format

---

geode-benchmarks/build.gradle
geode-benchmarks/src/main/java/org/apache/geode/benchmark/parameters/GcParameters.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/parameters/HeapParameters.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/topology/ClientServerTopologyWithRouterAndSniProxy.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/topology/ClientServerTopologyWithSniProxy.java
geode-benchmarks/src/main/java/org/apache/geode/benchmark/topology/Topology.java
geode-benchmarks/src/test/java/org/apache/geode/benchmark/parameters/GcParametersTest.java
geode-benchmarks/src/test/java/org/apache/geode/benchmark/parameters/HeapParametersTest.java
geode-benchmarks/src/test/java/org/apache/geode/benchmark/tests/ClientServerBenchmarkTest.java
geode-benchmarks/src/test/java/org/apache/geode/benchmark/topology/ClientServerTopologyTest.java
geode-benchmarks/src/test/java/org/apache/geode/benchmark/topology/ClientServerTopologyWithSniProxyTest.java
harness/build.gradle
harness/src/main/java/org/apache/geode/perftest/BenchmarkProperties.java
harness/src/main/java/org/apache/geode/perftest/TestConfig.java
harness/src/main/java/org/apache/geode/perftest/TestRunners.java
harness/src/main/java/org/apache/geode/perftest/WorkloadConfig.java
harness/src/main/java/org/apache/geode/perftest/jvms/JVMLauncher.java
harness/src/main/java/org/apache/geode/perftest/runner/DefaultTestRunner.java
harness/src/test/java/org/apache/geode/perftest/BenchmarkPropertiesTest.java
harness/src/test/java/org/apache/geode/perftest/TestRunnerIntegrationTest.java
infrastructure/src/main/java/org/apache/geode/infrastructure/BenchmarkMetadata.java
infrastructure/src/main/java/org/apache/geode/infrastructure/aws/LaunchCluster.java

Converting all of the system properties we use in the benchmarks to start with the benchmark
prefix. Changing the gradle build to copy all benchmark.* properties as system
roperties in the test.
For now, also copying the old set of withXXX properties to not break peoples scripts or CI.
Adding a way to automatically set system properties in test JVMs. Just add a property
with the prefix benchmark.system.ROLE, where ROLE is the role of jvms to target. Eg
benchmark.system.server.gemfire.disablePartitionedRegionBucketAck=true would set
gemfire.disablePartitionedRegionBucketAck=true  in the server JVMs.
Getting rid of problematic org.json dependency, and also making
sure we capture *all* system properties that might effect the behavior of the
test.

GEODE-9176: Automatically pass properties to benchmark JVMs

---

geode-benchmarks/src/test/java/org/apache/geode/benchmark/redis/topology/ManualRedisTopologyTest.java

Hosts and ports are currently configurable for `ManualRedisTopology`, adding a test verifying this behavior.

Add ManualRedisTopology test for hosts and ports

---

harness/src/main/java/org/apache/geode/perftest/infrastructure/ssh/SshInfrastructure.java

- This makes up almost ALL of the run output which doesn't seem to serve
any useful purpose.

Remove file copy logging

---

geode-benchmarks/src/main/java/org/apache/geode/benchmark/redis/tasks/StartGeodeServer.java

Use system properties to configure the redis server, instead of the gemfire
properties, which have now been removed.

GEODE-10126: Use system properties to configure redis

---

harness/src/main/java/org/apache/geode/perftest/yardstick/hdrhistogram/HdrHistogramWriter.java

Configure HistogramLogProcessor to throw exceptions rather than exit.

GEODE-10296: Prevent JVM exit on parser error.
